### ISSUE TITLE
old version of redcoin macosx? 

### ISSUE THREAD

**Issue by fourcolors** [reddcoin-project/reddcoin-3.10#105]
Am I missing something? The website leads me to believe that this is the wallet I'd download.

https://www.reddcoin.com/reddwallet/

But when I download the wallet I get this https://www.evernote.com/l/AA4IHczqbblIYr6x4jZF4SJl7ZcL8But3FU

**Comment by lionzeye** [comment]
ReddWallet was a proof of concept for a different type of wallet. Its development has been idle since early 2015. The wallet you've downloaded is the current desktop wallet and is the most complete and stable version you can use. We are working on a wallet somewhat similar to the ReddWallet concept though, so if you like what you see in those screenshots: there's an alternative on the way.

**Comment by TechAdeptRDD** [comment]
https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/
