### ISSUE TITLE
Importing from bootstrap.dat takes hours and hours

### ISSUE THREAD

**Issue by 1RedOne** [reddcoin-project/reddcoin-3.10#109]
Why does it take such a long time to process a bootstrap.dat file?

In the time span that this sat processing (more than eight hours now) I completely synced the entire 28GB of the monero blockchain.   That is completely bonkers.  Also, it's only now synced up to 1 year and 25 weeks behind.  It's been **hours**.

**Comment by HenryYoung42** [comment]
It takes so long because Reddcoin Core 2.0 is based on Bitcoin 0.9. There has need at least an order of magnitude decrease in sync times by Bitcoin 0.15. I am working on an alternative implementation called Reddcoin Fast which will be based on Bitcoin 0.15.1 with Reddcoin PoSV reintegrated. It will use the exact same blockchain. It will also bring many other modern day Bitcoin features to Reddcoin, which otherwise is lagging badly.

**Comment by 1RedOne** [comment]
Sounds great!  The wallet worked once it was synced, but the UI hanging
during the import, and the incredibly slow import as well (I'm not saying
the file is too big, it just takes 18 hours to process a .dat file on a
very fast system with SSD storage...doesn't make sense).

**Comment by acrive82** [comment]
Take hours? Or totally stuck? I see changes only if I kill the process and re-start again.

**Comment by 1RedOne** [comment]
That's the same issue I see, in fact. The client locks up entirely while
processing the file.  This is a simple threading operation, just add a
runspace to handle UX and another for data intensive tasks.

**Comment by reddink** [comment]
@1RedOne closing issue,
A number of implementations are working to improve sync times of the blockchain (including Reddcoin Core)
