### ISSUE TITLE
I don't receive my rewards 

### ISSUE THREAD

**Issue by EnacheLucian** [reddcoin-project/reddcoin-3.10#123]
it is a while now that this problem persists . And I really think to don't sustain the network no more.The users are sustaining the network because of the rewards they get from staking(creating blocks), in my case I don't get a reward for long time now. Maybe I must update something , maybe I do something wrong...Pls help! thx! 
 all the blocks that I generate when I wait for reward :false 👎

**Comment by lionzeye** [comment]
Staking remains a bit of a lottery, if your wallet's 'weight' is significantly lower than other staking wallets on the network, your chances of receiving rewards are naturally lower. If energy cost is an issue: does the yearly interest rate of ~5% outweigh the energy costs in your case?

**Comment by EnacheLucian** [comment]
it is true , my wallet 'weight' is only 100k , but before that I received some reward every 3/4 days, from then all my blocks are refusing to go in the chain. I updated my version of the wallet right now (v2) do you think it matters? thx

**Comment by EnacheLucian** [comment]
I mean I have 100k coins RDD, my weight it is 2032984. sorry

**Comment by CagatayUlubay** [comment]
I have 100k too in my main wallet and it takes ~2weeks now to receive a reward.

Since there are more and more RDD coming into the pot, it also decreases the chances to actually win a stake. Also if you have them for "too long" the chances decreasing even more, which should make you want to trade them more.

Look here: https://agroff.github.io/posv/#weightGraphAge  

You can see that at the first 2 weeks you get weight faster and after that you will get less weight compared to PoS. In the end, the longer you stake your coins, the slower your chances will increase to win a stake.

Since you will always get ~5% a year, it shouldn't matter when you win, since you will win more RDD the longer it took you. So like winning every day would be like 1k RDD while winning every 10days would be 10k RDD (just a poor example).

**Comment by EnacheLucian** [comment]
to much thx! the link was helpful and I get it how it is working!  take care man and thx again.

**Comment by reddink** [comment]
Thankyou for the inputs,
Closing issue
