### ISSUE TITLE
Reddcoin core wallet 3.01 Windows 10  installation issues

### ISSUE THREAD

**Issue by Aschettini** [reddcoin-project/reddcoin-3.10#156]
1) it is required to run the instal program as Administrator, otherwise it fails.
2) There is no way to verify what i the data directory that will be used as default.
3) The default data directory is not known %APPDATA%/Reddcoin/ but it actually proved to be wrong.
4) After downloading the #bootstrap.dat files on the indicated directory the sync still takes ages.
5) I had to call the program by command line with the -choosedatafile modifier , that is the only way to choose the %APPDATA%/Reddcoin/ directory.
6) The application is taking ages to index the file ( and not understood why it requires tit if the process was followed to extract the files from the *.zip file to save sync time.

**Comment by reddink** [comment]
Thanks for raising these windows issues.
Items 1, 2, 3, 5 are relating to the fact that the Reddcoin Core install script runs with elevated privileges, unfortunately if the user chooses to launch Reddcoin Core at the end of the install, it is also launched with the same elevated privileges.

The solution is to modify the script so that explorer.exe launches Reddcoin Core. Similar approach to what [http://nsis.sourceforge.net/ShellExecAsUser_plug-in](http://nsis.sourceforge.net/ShellExecAsUser_plug-in) does, but without a plugin.

Items 4, 6 the bootstrap.dat file does not contain the index data, it only contains raw block data, so once imported, it will also create the index.
There is a repository containing the fully index data. [https://github.com/reddcoin-project/bootstrap_files](https://github.com/reddcoin-project/bootstrap_files)
